---
title: "Assignment#3_Logistic Regression"
author: "Viva"
date: "`r Sys.Date()`"
output:
  html_document:
    keep_md: yes
    toc: yes
    theme: flatly
    toc_float: yes
    code_folding: hide
    number_sections: no
  pdf_document:
    toc: yes
---

<style>
.kable thead tr th, .table thead tr th {
  text-align: left !important;}
table.kable, table.table {
  width: 100% !important;}
  body {
  line-height: 1.6;
  font-size: 16px
}
</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  cache = TRUE,
  dpi = 150)
options(scipen = 999)

if(!require(pacman)){install.packages("pacman"); library(pacman)}
p_load(tidyverse, sf, units, nngeo, tmap, tinytex, kableExtra, janitor, classInt,
       patchwork, here, tidycensus, lwgeom, lsr, haven, descr, RColorBrewer, stargazer,
       car, FNN, GGally, MASS, ISLR2, spdep, caret, ckanr, grid, gridExtra, ggcorrplot,
       jtools, broom, tufte, rmarkdown, corrr, RSocrata, viridis, spatstat, raster, knitr,
       arm, mlogit, readxl, lubridate)

library(conflicted)
conflicts_prefer(dplyr::select)
conflicts_prefer(dplyr::filter)
conflicts_prefer(dplyr::recode)
```

# Question 1
## Choose variable
```{r variable}
# Viva's path
all <- read_csv('/Users/Viva Wan/Documents/GitHub/Local/cpln505_assignment3_voting_data.csv')
# Yaohan's path
all <- read_csv('/Users/Viva Wan/Documents/GitHub/Local/cpln505_assignment3_voting_data.csv')

dat <- all %>%
  select(VCF0004,VCF0704a,
         VCF0101,VCF0103,VCF0104,VCF0105a,VCF0128,VCF0114,VCF0140a,VCF0148a,VCF0108,
         VCF0878,VCF9239,VCF0656,
         VCF0302,VCF0113) %>%
  filter(VCF0004 == 2012 | VCF0004 == 2016) %>%
  rename(# target variables
         year = VCF0004,
         candidate = VCF0704a, 
         # demographics
         age = VCF0101,
         birth = VCF0103,
         gender = VCF0104,
         race = VCF0105a,
         religion = VCF0128,
         income = VCF0114,
         education = VCF0140a,
         class = VCF0148a,
         hispanic = VCF0108,
         # political ideology
         lgbt = VCF0878,
         gun = VCF9239,
         trust = VCF0656,
         # Political Affiliation
         party = VCF0302,
         south = VCF0113)%>%
  filter(candidate != 0,
         !(gender %in% c(0,3)), 
           race != 9,
           birth !=0,
           religion !=0,
           income != 0,
           education!=9, 
           class != 9, 
           !(hispanic %in% c(8,9)),
           !(lgbt %in% c(9)), 
           !(gun %in% c(-8,-9)),
           trust != 999,
           !(party %in% c(8,9))) %>%
  na.omit() %>%
  mutate(candidate = as.factor(recode(candidate,
                                     `1` = 'democrat',
                                     `2` = 'republican')),
         gender = as.factor(recode(gender,
                                       `1` = 'male',
                                       `2` = 'female')),
         birth = as.factor(recode(birth,
                                  `1`='after1991',
                                  `2`='1975-1990',
                                  `3`='1959-1974',
                                  `4`='1943-1958',
                                  `5`='1927-1942',
                                  `6`='1911-1926',
                                  `7`='1895-1910',
                                  `8`='Before1895')),
         race = as.factor(recode(race,
                                 `1`='White',
                                 `2`='Black',
                                 `3`='Asian',
                                 `4`='Indian',
                                 `5`='Hispanic',
                                 `6`='Other')),
         religion = as.factor(recode(religion,
                                     `1`='Protestant',
                                     `2`='Roman Catholic',
                                     `3`='Jewish',
                                     `4`='Other')),
         income = as.factor(recode(income,
                                   `1`='0-16th',
                                   `2`='17-33rd',
                                   `3`='34-67th',
                                   `4`='68-95th',
                                   `5`='96-100th')),
         education = as.factor(recode(education,
                                   `1`='1-8th-grade',
                                   `2`='2-9-12th-grade',
                                   `3`='3-high-school',
                                   `4`='4-training',
                                   `5`='5-no-degree',
                                   `6`='6-bachelor',
                                   `7`='7-advanced')),
         class = as.factor(recode(class,
                                  `1`='1ave-working',
                                  `2`='2working',
                                  `3`='3upper-working',
                                  `4`='4ave-middle',
                                  `5`='5middle',
                                  `6`='6upper-middle')),
         hispanic = as.factor(recode(hispanic,
                                       `1` = 'hispanic',
                                       `2` = 'non-hispanic')),
         lgbt = as.factor(recode(lgbt,
                                 `1` = 'yes',
                                 `2` = 'no',
                                 `3` = 'dk')),
         gun = as.factor(recode(gun,
                                `1` = 'extreme',
                                `2` = 'very',
                                `3` = 'somewhat',
                                `4`='not-too',
                                `5`='not-at-all')),
         trust = factor(case_when(
           trust == 0 ~ "no",
           trust <= 25 & trust >0 ~ "not-too",
           trust <= 50 & trust > 25 ~ "some",
           trust <= 75 & trust > 50 ~ "very",
           trust >75 ~ "extreme")),
         party = as.factor(recode(party,
                                `5`='democrat',
                                `1` = 'republican',
                                `2` = 'Independent',
                                `3` = 'none',
                                `4`='other')),
         south = as.factor(recode(south,
                                 `1` = 'south',
                                 `2` = 'non-south')))

dat.12 <- subset(dat[dat$year == 2012,]) 
dat.16 <- subset(dat[dat$year == 2016,])
```

## reclassify variable
```{r reclassify 2012}
reclassify.var <- c('birth','race','income','education','class')
plot.12 <- list()

for (i in 1:length(reclassify.var)) {
  var = reclassify.var[i]
  
  plot.12[[i]] <- dat.12 %>%
    select(candidate, !!sym(var)) %>% na.omit() %>%
    group_by(candidate,!!sym(var)) %>%
    summarize(count.vote = n(), .groups = 'drop') %>%
    group_by(!!sym(var))%>%
    mutate(percentage = round(count.vote/sum(count.vote)*100), digit= 0)%>%
    ungroup()%>%
      ggplot(aes(!!sym(var),percentage)) +
        geom_bar(aes(fill= candidate), position="dodge", stat="identity") +
        scale_fill_viridis(discrete = TRUE) +
        labs(title = paste("Percentage of Voting by", var, "in 2012")) +
        theme_bw()+
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
  
  print(plot.12[[i]])
}

dat.12 <- dat.12 %>% 
  mutate(
    birth = factor(case_when(
      birth %in% c('1911-1926', '1927-1942') ~ '1911-1942',
      birth %in% c('1943-1958', '1959-1974') ~ '1943-1974',
      birth %in% c('1975-1990', 'after199') ~ 'after1975')),
    race = factor(case_when(
      race == 'White' ~ 'white',
      race == 'Black' ~ 'black',
      !(race %in% c('White','Black')) ~ 'others'),
      
    
         )
  

```


# Question 2

## Choose variables

```{r variable_2}
# load HHTS datasets
hh <- read_excel(here::here("data/raw/1_Household_Public.xlsx"))
per <- read_excel(here::here("data/raw/2_Person_Public.xlsx"))
veh <- read_excel(here::here("data/raw/3_Vehicle_Public.xlsx"))
trip <- read_excel(here::here("data/raw/4_Trip_Public.xlsx"))

## trip dataset
trip_work <- trip %>%
  filter(D_LOC_TYPE == 2 & MODE_AGG %in% c(2,3,5))%>% # destination location type & mode aggregated
  mutate(mode_cat = as.factor(recode(MODE_AGG,
    `3` = "car",
    `2` = "bike",
    `5` = "transit")))%>%
  group_by(PERSON_ID) %>%
  slice(1) %>% # keep only the first row for each group
  ungroup()%>% # optionally, ungroup the data frame
  select(HH_ID, 
         PERSON_ID,
         mode_cat,
         Model_TravTime,
         Model_TravDist) %>%
  rename(travel_dist = Model_TravDist,
    travel_time = Model_TravTime) %>%
  filter(!is.na(travel_time) & !is.na(travel_dist))

table(is.na(trip_work$travel_time))
table(is.na(trip_work$travel_time))

## person dataset
per_work <- per %>%
  filter(GEND != 99) %>%
  mutate(gender_cat = as.factor(recode(GEND, # recode gender
                         `1` = 'male',
                         `2` = 'female'))) %>%
  filter(AGECAT < 98) %>%
  mutate(age_cat = as.factor(recode(AGECAT, # recode age
                      `1` = '0-5',
                      `2` = '6-12',
                      `3` = '13-15',
                      `4` = '16-17',
                      `5` = '18-24',
                      `6` = '25-34',
                      `7` = '35-44',
                      `8` = '45-54',
                      `9` = '55-64',
                      `10` = '65-74',
                      `11` = '75-85',
                      `12` = '86+'))) %>%
  filter(RACE != 98 & RACE != 99) %>%
  mutate(race_cat = as.factor(recode(RACE, # recode race
                      `1` = 'white',
                      `2` = 'black',
                      `3` = 'hispanic',
                      `4` = 'american indian',
                      `5` = 'asian',
                      `6` = 'native hawaiian',
                      `97` = 'others',
                      `100` = 'multi-race',
                      `988` = 'pilot'))) %>%
  filter(EDUCA < 98) %>%
  mutate(edu_cat = as.factor(recode(EDUCA, # recode education
                      `1` = 'less than high school',
                      `2` = 'high school',
                      `3` = 'college no degree',
                      `4` = 'technical school',
                      `5` = 'bachelor',
                      `6` = 'graduate',
                      `97` = 'others'))) %>%
  filter(LIC < 98) %>%
  mutate(lic_dum = as.factor(recode(LIC, # recode driver license status
                      `1` = 'yes',
                      `2` = 'no'))) %>%
  filter(PARK_SUB < 8) %>%
  mutate(park_sub_cat = as.factor(recode(PARK_SUB, # recode parking subsidy
                           `2` = 'pay',
                           `1` = 'subsidize',
                           `3` = 'free'))) %>%
  filter(TRAN_SUB < 8) %>%
  mutate(transit_sub_cat = as.factor(recode(TRAN_SUB, # recode transit subsidy
                              `2` = 'pay',
                              `1` = 'subsidize'))) %>%
  select(HH_ID, PERSON_ID,
        gender_cat, age_cat, race_cat, edu_cat, lic_dum, park_sub_cat, transit_sub_cat)

## household dataset
hh_work <- hh %>%
  filter(OP_VEH <= TOT_VEH) %>%
  select(HH_ID, # household ID
         OP_VEH, # total household vehicles in working condition
         TOT_BIKE, # number of bicycles in household
         TOLL_ACCNT, # household maintains toll road/bridge account
         CAR_SHARE, # household maintains a car sharing membership/rents cars
         INCOME # household income
         ) %>%
  filter(OP_VEH < 98 & TOT_BIKE < 98 & TOLL_ACCNT < 98 & CAR_SHARE < 98 & INCOME < 98) %>%
  rename(veh_num = OP_VEH,
         bike_num = TOT_BIKE,
         toll_accnt = TOLL_ACCNT,
         car_share = CAR_SHARE,
         income = INCOME) %>%
  mutate(toll_accnt_dum = as.factor(recode(toll_accnt,
                            `1` = 'yes',
                            `2` = 'no')),
         car_share_dum = as.factor(recode(car_share,
                            `1` = 'yes',
                            `2` = 'no')),
         income = as.factor(recode(income,
                            `1` = '$0 to $9,999',
                            `2` = '$10,000 to $24,999',
                            `3` = '$25,000 to $34,999',
                            `4` = '$35,000 to $49,999',
                            `5` = '$50,000 to $74,999',
                            `6` = '$75,000 to $99,999',
                            `7` = '$100,000 to $149,999',
                            `8` = '$150,000 to $199,999',
                            `9` = '$200,000 to $249,999',
                            `10` = '$250,000 or more')))

# combine three datasets
dat <- trip_work %>%
  left_join(per_work, by = c("PERSON_ID", "HH_ID")) %>%
  left_join(hh_work, by = "HH_ID") %>%
  filter_all(all_vars(!is.na(.))) %>% # remove all NAs
  filter(travel_dist < 10 & travel_time < 120) # remove outliers (people who travel < 10 miles and < 120 minutes)

table(dat$mode_cat)
```

## Calculate travel time and travel costs

```{r time_cost}
# calculate average speed for each mode
ave.speed <- dat %>% group_by(mode_cat) %>%
  summarise(ave_speed = mean(travel_dist/(travel_time/60)))

# calculate travel time for alternative modes
dat.car <- dat %>% filter(mode_cat == "car")
dat.transit <- dat %>% filter(mode_cat == "transit")
dat.bike <- dat %>% filter(mode_cat == "bike")

dat.car$time.car <- dat.car$travel_time
dat.car$time.transit <- 60*(dat.car$travel_dist/ave.speed$ave_speed[3]) + 10 # add 10 minutes for waiting and walking to station
dat.car$time.bike <- 60*(dat.car$travel_dist/ave.speed$ave_speed[1])

dat.transit$time.transit <- dat.transit$travel_time + 10
dat.transit$time.car <- 60*(dat.transit$travel_dist/ave.speed$ave_speed[2])
dat.transit$time.bike <- 60*(dat.transit$travel_dist/ave.speed$ave_speed[1])

dat.bike$time.bike <- dat.bike$travel_time
dat.bike$time.car <- 60*(dat.bike$travel_dist/ave.speed$ave_speed[2])
dat.bike$time.transit <- 60*(dat.bike$travel_dist/ave.speed$ave_speed[3]) + 10

```
