---
title: "Assignment#3_Logistic Regression"
author: "Viva/Yaohan"
date: "`r Sys.Date()`"
output:
  html_document:
    keep_md: yes
    toc: yes
    theme: flatly
    toc_float: yes
    code_folding: hide
    number_sections: no
  pdf_document:
    toc: yes
---

<style>
.kable thead tr th, .table thead tr th {
  text-align: left !important;}
table.kable, table.table {
  width: 100% !important;}
  body {
  line-height: 1.6;
  font-size: 16px
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  cache = TRUE,
  dpi = 150)
options(scipen = 999)

if(!require(pacman)){install.packages("pacman"); library(pacman)}
p_load(tidyverse, sf, units, nngeo, tmap, tinytex, kableExtra, janitor, classInt,
       patchwork, here, tidycensus, lwgeom, lsr, haven, descr, RColorBrewer, stargazer,
       car, FNN, GGally, MASS, ISLR2, spdep, caret, ckanr, grid, gridExtra, ggcorrplot,
       jtools, broom, tufte, rmarkdown, corrr, RSocrata, viridis, spatstat, raster, knitr,
       arm, mlogit, readxl, lubridate)

library(conflicted)
conflicts_prefer(dplyr::select)
conflicts_prefer(dplyr::filter)
conflicts_prefer(dplyr::recode)
```


# Question 2

## Choose variables

```{r variable_2}
# load HHTS datasets
hh <- read_excel(here::here("data/raw/1_Household_Public.xlsx"))
per <- read_excel(here::here("data/raw/2_Person_Public.xlsx"))
veh <- read_excel(here::here("data/raw/3_Vehicle_Public.xlsx"))
trip <- read_excel(here::here("data/raw/4_Trip_Public.xlsx"))

## trip dataset
trip_work <- trip %>%
  filter(D_LOC_TYPE == 2 & MODE_AGG %in% c(2,3,5))%>% # destination location type & mode aggregated
  mutate(mode_cat = as.factor(recode(MODE_AGG,
    `3` = "car",
    `2` = "bike",
    `5` = "transit")))%>%
  group_by(PERSON_ID) %>%
  slice(1) %>% # keep only the first row for each group
  ungroup()%>% # optionally, ungroup the data frame
  select(HH_ID, 
         PERSON_ID,
         mode_cat,
         Model_TravTime,
         Model_TravDist) %>%
  rename(travel_dist = Model_TravDist,
    travel_time = Model_TravTime) %>%
  filter(!is.na(travel_time) & !is.na(travel_dist))

table(is.na(trip_work$travel_time))
table(is.na(trip_work$travel_time))

## person dataset
per_work <- per %>%
  filter(GEND != 99) %>%
  mutate(gender_cat = as.factor(recode(GEND, # recode gender
                         `1` = 'male',
                         `2` = 'female'))) %>%
  filter(AGECAT < 98) %>%
  mutate(age_cat = as.factor(recode(AGECAT, # recode age
                      `1` = '0-5',
                      `2` = '6-12',
                      `3` = '13-15',
                      `4` = '16-17',
                      `5` = '18-24',
                      `6` = '25-34',
                      `7` = '35-44',
                      `8` = '45-54',
                      `9` = '55-64',
                      `10` = '65-74',
                      `11` = '75-85',
                      `12` = '86+'))) %>%
  filter(RACE != 98 & RACE != 99 & RACE != 988) %>%
  mutate(race_cat = as.factor(recode(RACE, # recode race
                      `1` = 'white',
                      `2` = 'black',
                      `3` = 'hispanic',
                      `4` = 'american indian',
                      `5` = 'asian',
                      `6` = 'native hawaiian',
                      `97` = 'others',
                      `100` = 'multi-race'))) %>%
   mutate(race_cat = factor(race_cat,
    levels = c('white', 'black', 'hispanic','american indian','asian','native hawaiian','multi-race','others'))) %>%
  filter(EDUCA < 98) %>%
  mutate(edu_cat = as.factor(recode(EDUCA, # recode education
                      `1` = 'less than high school',
                      `2` = 'high school',
                      `3` = 'college no degree',
                      `4` = 'technical school',
                      `5` = 'bachelor',
                      `6` = 'graduate',
                      `97` = 'others'))) %>%
  mutate(edu_cat = factor(edu_cat,
  levels = c('less than high school', 'high school', 'college no degree','technical school','bachelor','graduate','others'))) %>%
  filter(LIC < 98) %>%
  mutate(lic_dum = as.factor(recode(LIC, # recode driver license status
                      `1` = 'yes',
                      `2` = 'no'))) %>%
  filter(PARK_SUB < 8) %>%
  mutate(park_sub_cat = as.factor(recode(PARK_SUB, # recode parking subsidy
                           `2` = 'pay',
                           `1` = 'subsidize',
                           `3` = 'free'))) %>%
  filter(TRAN_SUB < 8) %>%
  mutate(transit_sub_cat = as.factor(recode(TRAN_SUB, # recode transit subsidy
                              `2` = 'pay',
                              `1` = 'subsidize'))) %>%
  select(HH_ID, PERSON_ID,
        gender_cat, age_cat, race_cat, edu_cat, lic_dum, park_sub_cat, transit_sub_cat)

## household dataset
hh_work <- hh %>%
  filter(OP_VEH <= TOT_VEH) %>%
  select(HH_ID, # household ID
         OP_VEH, # total household vehicles in working condition
         TOT_BIKE, # number of bicycles in household
         TOLL_ACCNT, # household maintains toll road/bridge account
         CAR_SHARE, # household maintains a car sharing membership/rents cars
         INCOME # household income
         ) %>%
  filter(OP_VEH < 98 & TOT_BIKE < 98 & TOLL_ACCNT < 98 & CAR_SHARE < 98 & INCOME < 98) %>%
  rename(veh_num = OP_VEH,
         bike_num = TOT_BIKE,
         toll_accnt = TOLL_ACCNT,
         car_share = CAR_SHARE,
         income = INCOME) %>%
  mutate(toll_accnt_dum = as.factor(recode(toll_accnt,
                            `1` = 'yes',
                            `2` = 'no')),
         car_share_dum = as.factor(recode(car_share,
                            `1` = 'yes',
                            `2` = 'no')),
         income_cat = as.factor(recode(income,
                            `1` = '$0 to $9,999',
                            `2` = '$10,000 to $24,999',
                            `3` = '$25,000 to $34,999',
                            `4` = '$35,000 to $49,999',
                            `5` = '$50,000 to $74,999',
                            `6` = '$75,000 to $99,999',
                            `7` = '$100,000 to $149,999',
                            `8` = '$150,000 to $199,999',
                            `9` = '$200,000 to $249,999',
                            `10` = '$250,000 or more')),
         veh_num_cat = as.factor(veh_num),
         bike_num_cat = as.factor(bike_num)) %>%
  mutate(income_cat = factor(income_cat,
  levels = c('$0 to $9,999', '$10,000 to $24,999', '$25,000 to $34,999','$35,000 to $49,999','$50,000 to $74,999','$75,000 to $99,999','$100,000 to $149,999', '$150,000 to $199,999', '$200,000 to $249,999','$250,000 or more'))) %>%
  select(-income, -toll_accnt, -car_share)

# combine three datasets
dat <- trip_work %>%
  left_join(per_work, by = c("PERSON_ID", "HH_ID")) %>%
  left_join(hh_work, by = "HH_ID") %>%
  filter_all(all_vars(!is.na(.))) %>% # remove all NAs
  filter(travel_dist < 10 & travel_time < 120) # remove outliers (people who travel < 10 miles and < 120 minutes)

table(dat$mode_cat)
```

## Calculate travel time and travel costs

```{r time_cost}
# calculate average speed for each mode
ave.speed <- dat %>% group_by(mode_cat) %>%
  summarise(ave_speed = mean(travel_dist/(travel_time/60)))

# calculate travel time for alternative modes
dat.car <- dat %>% filter(mode_cat == "car")
dat.transit <- dat %>% filter(mode_cat == "transit")
dat.bike <- dat %>% filter(mode_cat == "bike")

dat.car$time.car <- dat.car$travel_time
dat.car$time.transit <- 60*(dat.car$travel_dist/ave.speed$ave_speed[3]) + 10 # add 10 minutes for waiting and walking to station
dat.car$time.bike <- 60*(dat.car$travel_dist/ave.speed$ave_speed[1])

dat.transit$time.transit <- dat.transit$travel_time + 10
dat.transit$time.car <- 60*(dat.transit$travel_dist/ave.speed$ave_speed[2])
dat.transit$time.bike <- 60*(dat.transit$travel_dist/ave.speed$ave_speed[1])

dat.bike$time.bike <- dat.bike$travel_time
dat.bike$time.car <- 60*(dat.bike$travel_dist/ave.speed$ave_speed[2])
dat.bike$time.transit <- 60*(dat.bike$travel_dist/ave.speed$ave_speed[3]) + 10

# make a subset of car to balance the mode split
set.seed(seed = 1)
rows <- sample(1:nrow(dat.car), 500)
dat.car <- dat.car[rows,]

dat <- rbind.data.frame(dat.car, dat.transit, dat.bike)

# calculate travel costs for alternative modes
## $0.6/mile for driving
dat$cost.car <- dat$travel_dist * 0.6

## multiply 0.5 for non-monetary costs, add $2 for ticket
dat$cost.transit <- dat$travel_dist * 0.5 + 2

## add $3 for non-monetary cost and wear and tear
dat$cost.bike <- dat$travel_dist + 3

table(dat$mode_cat)
```

## Reclassify variables

```{r reclassification_2}
dat <- dat %>%
  filter_all(all_vars(!is.na(.))) # remove all NAs

## age categories
dat %>%
  select(mode_cat, age_cat) %>%
  group_by(age_cat, mode_cat) %>%
  summarize(count.mode = n()) %>%
  ungroup() %>%
  group_by(age_cat) %>%
  mutate(per = round(count.mode/sum(count.mode)*100, digit= 2)) %>%
  ungroup() %>%
    ggplot(aes(age_cat, per)) +
      geom_bar(aes(fill= mode_cat), position="dodge", stat="identity") +
      scale_fill_viridis(discrete = TRUE) +
      labs(title = "Percentage of Mode Choice by Age Categories") +
      theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

table(dat$age_cat,dat$mode_cat)

### reclassification
dat <- dat %>%
  mutate(age_cat_re = factor(case_when(
    age_cat %in% c('0-5', '6-12', '13-15', '16-17', '18-24') ~ 'under 24',
    age_cat %in% c('25-34', '35-44', '45-54', '55-64') ~ '25-64',
    age_cat %in% c('65-74', '75-85', '86+') ~ 'above 65'),
    levels = c('under 24', '25-64', 'above 65')))

dat %>%
  select(mode_cat, age_cat_re) %>%
  group_by(age_cat_re, mode_cat) %>%
  summarize(count.mode = n()) %>%
  ungroup() %>%
  group_by(age_cat_re) %>%
  mutate(per = round(count.mode/sum(count.mode)*100, digit= 2)) %>%
  ungroup() %>%
    ggplot(aes(age_cat_re, per)) +
      geom_bar(aes(fill= mode_cat), position="dodge", stat="identity") +
      scale_fill_viridis(discrete = TRUE) +
      labs(title = "Percentage of Mode Choice by Age Categories (Reclassification)") +
      theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

table(dat$age_cat_re,dat$mode_cat)

## race categories
dat %>%
  select(mode_cat, race_cat) %>%
  group_by(race_cat, mode_cat) %>%
  summarize(count.mode = n()) %>%
  ungroup() %>%
  group_by(race_cat) %>%
  mutate(per = round(count.mode/sum(count.mode)*100, digit= 2)) %>%
  ungroup() %>%
    ggplot(aes(race_cat, per)) +
      geom_bar(aes(fill= mode_cat), position="dodge", stat="identity") +
      scale_fill_viridis(discrete = TRUE) +
      labs(title = "Percentage of Mode Choice by Race Categories") +
      theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

table(dat$race_cat,dat$mode_cat)

### reclassification
dat <- dat %>%
  mutate(race_cat_re = factor(case_when(
    race_cat %in% c('white') ~ 'white',
    race_cat %in% c('american indian', 'asian', 'black', 'hispanic', 'multi-race',
                    'native hawaiian', 'others') ~ 'non-white'),
    levels = c('white', 'non-white')))

dat %>%
  select(mode_cat, race_cat_re) %>%
  group_by(race_cat_re, mode_cat) %>%
  summarize(count.mode = n()) %>%
  ungroup() %>%
  group_by(race_cat_re) %>%
  mutate(per = round(count.mode/sum(count.mode)*100, digit= 2)) %>%
  ungroup() %>%
    ggplot(aes(race_cat_re, per)) +
      geom_bar(aes(fill= mode_cat), position="dodge", stat="identity") +
      scale_fill_viridis(discrete = TRUE) +
      labs(title = "Percentage of Mode Choice by Race Categories (Reclassification)") +
      theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

table(dat$race_cat_re,dat$mode_cat)

## education categories
dat %>%
  select(mode_cat, edu_cat) %>%
  group_by(edu_cat, mode_cat) %>%
  summarize(count.mode = n()) %>%
  ungroup() %>%
  group_by(edu_cat) %>%
  mutate(per = round(count.mode/sum(count.mode)*100, digit= 2)) %>%
  ungroup() %>%
    ggplot(aes(edu_cat, per)) +
      geom_bar(aes(fill= mode_cat), position="dodge", stat="identity") +
      scale_fill_viridis(discrete = TRUE) +
      labs(title = "Percentage of Mode Choice by Education Categories") +
      theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

table(dat$edu_cat,dat$mode_cat)

### reclassification
dat <- dat %>%
  mutate(edu_cat_re = factor(case_when(
    edu_cat %in% c('bachelor', 'graduate') ~ 'bachelor or higher',
    edu_cat %in% c('college no degree', 'high school', 'less than high school',
                   'others', 'technical school') ~ 'without bachelor')))

dat %>%
  select(mode_cat, edu_cat_re) %>%
  group_by(edu_cat_re, mode_cat) %>%
  summarize(count.mode = n()) %>%
  ungroup() %>%
  group_by(edu_cat_re) %>%
  mutate(per = round(count.mode/sum(count.mode)*100, digit= 2)) %>%
  ungroup() %>%
    ggplot(aes(edu_cat_re, per)) +
      geom_bar(aes(fill= mode_cat), position="dodge", stat="identity") +
      scale_fill_viridis(discrete = TRUE) +
      labs(title = "Percentage of Mode Choice by Education Categories (Reclassification)") +
      theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

table(dat$edu_cat_re,dat$mode_cat)

## income categories
dat %>%
  select(mode_cat, income_cat) %>%
  group_by(income_cat, mode_cat) %>%
  summarize(count.mode = n()) %>%
  ungroup() %>%
  group_by(income_cat) %>%
  mutate(per = round(count.mode/sum(count.mode)*100, digit= 2)) %>%
  ungroup() %>%
    ggplot(aes(income_cat, per)) +
      geom_bar(aes(fill= mode_cat), position="dodge", stat="identity") +
      scale_fill_viridis(discrete = TRUE) +
      labs(title = "Percentage of Mode Choice by Income Categories") +
      theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

table(dat$income_cat,dat$mode_cat)

### reclassification
dat <- dat %>%
  mutate(income_cat_re = factor(case_when(
    income_cat %in% c('$0 to $9,999', '$10,000 to $24,999', '$25,000 to $34,999',
                      '$35,000 to $49,999') ~ 'low income',
    income_cat %in% c('$50,000 to $74,999', '$75,000 to $99,999', '$100,000 to $149,999')
    ~ 'middle income',
    income_cat %in% c('$150,000 to $199,999', '$200,000 to $249,999', '$250,000 or more')
    ~ 'high income'),
    levels = c('low income', 'middle income', 'high income')))

dat %>%
  select(mode_cat, income_cat_re) %>%
  group_by(income_cat_re, mode_cat) %>%
  summarize(count.mode = n()) %>%
  ungroup() %>%
  group_by(income_cat_re) %>%
  mutate(per = round(count.mode/sum(count.mode)*100, digit= 2)) %>%
  ungroup() %>%
    ggplot(aes(income_cat_re, per)) +
      geom_bar(aes(fill= mode_cat), position="dodge", stat="identity") +
      scale_fill_viridis(discrete = TRUE) +
      labs(title = "Percentage of Mode Choice by Income Categories (Reclassification)") +
      theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

table(dat$income_cat_re,dat$mode_cat)

## total household vehicles in working condition
dat %>%
  select(mode_cat, veh_num_cat) %>%
  group_by(veh_num_cat, mode_cat) %>%
  summarize(count.mode = n()) %>%
  ungroup() %>%
  group_by(veh_num_cat) %>%
  mutate(per = round(count.mode/sum(count.mode)*100, digit= 2)) %>%
  ungroup() %>%
    ggplot(aes(veh_num_cat, per)) +
      geom_bar(aes(fill= mode_cat), position="dodge", stat="identity") +
      scale_fill_viridis(discrete = TRUE) +
      labs(title = "Percentage of Mode Choice by Total Household Vehicles in Working Condition") +
      theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

table(dat$veh_num_cat,dat$mode_cat)

### reclassification
dat <- dat %>%
  mutate(veh_num_cat_re = factor(case_when(
    veh_num_cat %in% c('0') ~ 'no vehicles',
    veh_num_cat %in% c('1') ~ 'one vehicle',
    veh_num_cat %in% c('2', '3', '4', '5') ~ 'two vehicles or more')))

dat %>%
  select(mode_cat, veh_num_cat_re) %>%
  group_by(veh_num_cat_re, mode_cat) %>%
  summarize(count.mode = n()) %>%
  ungroup() %>%
  group_by(veh_num_cat_re) %>%
  mutate(per = round(count.mode/sum(count.mode)*100, digit= 2)) %>%
  ungroup() %>%
    ggplot(aes(veh_num_cat_re, per)) +
      geom_bar(aes(fill= mode_cat), position="dodge", stat="identity") +
      scale_fill_viridis(discrete = TRUE) +
      labs(title = "Percentage of Mode Choice by Total Household Vehicles in Working Condition (Reclassification)") +
      theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

table(dat$veh_num_cat_re,dat$mode_cat)

## number of bicycles in household
dat %>%
  select(mode_cat, bike_num_cat) %>%
  group_by(bike_num_cat, mode_cat) %>%
  summarize(count.mode = n()) %>%
  ungroup() %>%
  group_by(bike_num_cat) %>%
  mutate(per = round(count.mode/sum(count.mode)*100, digit= 2)) %>%
  ungroup() %>%
    ggplot(aes(bike_num_cat, per)) +
      geom_bar(aes(fill= mode_cat), position="dodge", stat="identity") +
      scale_fill_viridis(discrete = TRUE) +
      labs(title = "Percentage of Mode Choice by Number of Bicycles in Household") +
      theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

table(dat$bike_num_cat,dat$mode_cat)

### reclassification
dat <- dat %>%
  mutate(bike_num_cat_re = factor(case_when(
    bike_num_cat %in% c('0', '1') ~ 'zero or one bike',
    bike_num_cat %in% c('2', '3', '4') ~ 'two to four bikes',
    bike_num_cat %in% c('5', '6', '7', '8', '9', '12') ~ 'five bikes or more'),
    levels = c('zero or one bike', 'two to four bikes', 'five bikes or more')))

dat %>%
  select(mode_cat, bike_num_cat_re) %>%
  group_by(bike_num_cat_re, mode_cat) %>%
  summarize(count.mode = n()) %>%
  ungroup() %>%
  group_by(bike_num_cat_re) %>%
  mutate(per = round(count.mode/sum(count.mode)*100, digit= 2)) %>%
  ungroup() %>%
    ggplot(aes(bike_num_cat_re, per)) +
      geom_bar(aes(fill= mode_cat), position="dodge", stat="identity") +
      scale_fill_viridis(discrete = TRUE) +
      labs(title = "Percentage of Mode Choice by Number of Bicycles in Household (Reclassification)") +
      theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

## transit_sub_cat
dat <- dat %>%
  mutate(transit_sub_cat = factor(transit_sub_cat, levels = c('subsidize', 'pay')))

table(dat$bike_num_cat_re,dat$mode_cat)
```

## Build multinomial logistic model

### Initial variable selection

```{r multinomial_regression}
# shape data into correct format
dat.logit <- mlogit.data(dat, shape="wide", 
                      choice="mode_cat", 
                      varying=c(20:25))

names(dat.logit)

## age_cat & age_cat_re —> none
mod1.2 <- mlogit (mode_cat ~ cost + time | age_cat_re, data = dat.logit, reflevel = "car")
summary(mod1.2)

## race_cat & race_cat_re —> race_cat_re
mod2.2 <- mlogit (mode_cat ~ cost + time | race_cat_re, data = dat.logit, reflevel = "car")
summary(mod2.2)

## edu_cat & edu_cat_re —> edu_cat_re
mod3.1 <- mlogit (mode_cat ~ cost + time | edu_cat, data = dat.logit, reflevel = "car")
mod3.2 <- mlogit (mode_cat ~ cost + time | edu_cat_re, data = dat.logit, reflevel = "car")
stargazer(mod3.1, mod3.2, type = "text", star.cutoffs = c(0.05, 0.01, 0.001))

## veh_num & veh_num_cat & veh_num_cat_re —> veh_num
mod4.1 <- mlogit (mode_cat ~ cost + time | veh_num, data = dat.logit, reflevel = "car")
mod4.3 <- mlogit (mode_cat ~ cost + time | veh_num_cat_re, data = dat.logit, reflevel = "car")
stargazer(mod4.1, mod4.3, type = "text", star.cutoffs = c(0.05, 0.01, 0.001))

## bike_num & bike_num_cat & bike_num_cat_re —> bike_num
mod5.1 <- mlogit (mode_cat ~ cost + time | bike_num, data = dat.logit, reflevel = "car")
mod5.3 <- mlogit (mode_cat ~ cost + time | bike_num_cat_re, data = dat.logit, reflevel = "car")
stargazer(mod5.1, mod5.3, type = "text", star.cutoffs = c(0.05, 0.01, 0.001))

## income_cat & income_cat_re —> income_cat_re
mod6.1 <- mlogit (mode_cat ~ cost + time | income_cat, data = dat.logit, reflevel = "car")
mod6.2 <- mlogit (mode_cat ~ cost + time | income_cat_re, data = dat.logit, reflevel = "car")
stargazer(mod6.1, mod6.2, type = "text", star.cutoffs = c(0.05, 0.01, 0.001))

```

### Summary table

```{r summary, fig.height=10, fig.width=16}
# continuous variables
dat_summary <- as.data.frame(dat.logit)[as.data.frame(dat.logit)$mode_cat, ]

dat_summary <- dat_summary %>%
  summarise(across(c(cost, time, veh_num, bike_num),
                   list(maximum = ~ max(., na.rm = TRUE),
                        minimum = ~ min(., na.rm = TRUE),
                        mean = ~ mean(., na.rm = TRUE),
                        standard_deviation = ~ sd(., na.rm = TRUE)),
                   .names = "{.col}:{.fn}")) %>%
  pivot_longer(cols = everything(), names_to = c("variables", "statistic"),
               names_sep = ":", values_to = "value") %>%
  mutate(value = round(value, digits = 2)) %>%
  pivot_wider(names_from = statistic, values_from = value)
write.csv(dat_summary, file = "/Users/yaohanxu/Documents/GitHub/CPLN5050_Planning_by_Numbers/output/Q2_Continuous.csv")

# categorical variables
## table
var_cat <- c('gender_cat', 'age_cat', 'race_cat', 'edu_cat','lic_dum','park_sub_cat','transit_sub_cat','toll_accnt_dum','car_share_dum','veh_num_cat', 'bike_num_cat','income_cat')
table_cat <- list()

for (i in 1:length(var_cat)){
  table_cat[[i]] <- dat %>%
    group_by(!!sym(var_cat[[i]])) %>%
    summarise(count = n()) %>%
    mutate(percentage = round(count/sum(count) * 100, digits = 2),
           variable = var_cat[[i]],
           category = as.character(!!sym(var_cat[[i]]))) %>%
    ungroup() %>%
    select(variable, category, count, percentage)}

cat_one <- bind_rows(table_cat)
write.csv(cat_one, file = "/Users/yaohanxu/Documents/GitHub/CPLN5050_Planning_by_Numbers/output/Q2_Categorical_1.csv")

## plot
plot_cat <- list()

for (i in 1:length(var_cat)) {
  plot_cat[[i]] <- dat %>%
    select(mode_cat, !!sym(var_cat[[i]])) %>% na.omit() %>%
    group_by(mode_cat, !!sym(var_cat[[i]])) %>%
    summarize(count.mode = n(), .groups = 'drop') %>%
    group_by(!!sym(var_cat[[i]]))%>%
    mutate(percentage = round(count.mode/sum(count.mode)*100), digit= 0)%>%
    ungroup()%>%
      ggplot(aes(!!sym(var_cat[[i]]),percentage)) +
        geom_bar(aes(fill= mode_cat), position="dodge", stat="identity") +
        scale_fill_viridis(discrete = TRUE) +
        theme_bw()+
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
}
wrap_plots(plot_cat, ncol = 3) + 
  plot_layout(guides = 'collect') +
  plot_annotation(title = "Percentage Distribution of Mode Choices by Categorical Variables",
                  theme = theme(plot.title = element_text(hjust = 0.5)))

# reclassified categorical variables
## table
var_cat_re <- c('age_cat_re', 'race_cat_re', 'edu_cat_re','veh_num_cat_re', 'bike_num_cat_re','income_cat_re')
table_cat <- list()

for (i in 1:length(var_cat_re)){
  table_cat[[i]] <- dat %>%
    group_by(!!sym(var_cat_re[[i]])) %>%
    summarise(count = n()) %>%
    mutate(percentage = round(count/sum(count) * 100, digits = 2),
           variable = var_cat_re[[i]],
           category = as.character(!!sym(var_cat_re[[i]]))) %>%
    ungroup() %>%
    select(variable, category, count, percentage)}

cat_two <- bind_rows(table_cat)
write.csv(cat_two, file = "/Users/yaohanxu/Documents/GitHub/CPLN5050_Planning_by_Numbers/output/Q2_Categorical_2.csv")

## plot
plot_cat <- list()

for (i in 1:length(var_cat_re)) {
  plot_cat[[i]] <- dat %>%
    select(mode_cat, !!sym(var_cat_re[[i]])) %>% na.omit() %>%
    group_by(mode_cat, !!sym(var_cat_re[[i]])) %>%
    summarize(count.mode = n(), .groups = 'drop') %>%
    group_by(!!sym(var_cat_re[[i]]))%>%
    mutate(percentage = round(count.mode/sum(count.mode)*100), digit= 0)%>%
    ungroup()%>%
      ggplot(aes(!!sym(var_cat_re[[i]]),percentage)) +
        geom_bar(aes(fill= mode_cat), position="dodge", stat="identity") +
        scale_fill_viridis(discrete = TRUE) +
        theme_bw()+
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
}
wrap_plots(plot_cat, ncol = 3) + 
  plot_layout(guides = 'collect') +
  plot_annotation(title = "Percentage Distribution of Mode Choices by Reclassified Categorical Variables",
                  theme = theme(plot.title = element_text(hjust = 0.5)))
```

### Final model

```{r final_model}
mod7 <- mlogit (mode_cat ~ cost + time | gender_cat + race_cat_re + edu_cat_re + lic_dum
                 + park_sub_cat + transit_sub_cat + veh_num + bike_num + toll_accnt_dum
                 + car_share_dum + income_cat_re, data = dat.logit, reflevel = "car")
summary(mod7)

## remove edu_cat_re
mod8 <- mlogit (mode_cat ~ cost + time | gender_cat + race_cat_re + lic_dum
                 + park_sub_cat + transit_sub_cat + veh_num + bike_num + toll_accnt_dum
                 + car_share_dum + income_cat_re, data = dat.logit, reflevel = "car")
summary(mod8)
lrtest(mod8, mod7)

## remove toll_accnt_dum
mod9 <- mlogit (mode_cat ~ cost + time | gender_cat + race_cat_re + lic_dum
                 + park_sub_cat + transit_sub_cat + veh_num + bike_num
                 + car_share_dum + income_cat_re, data = dat.logit, reflevel = "car")
summary(mod9)
lrtest(mod9, mod8)

## remove gender_cat
mod10 <- mlogit (mode_cat ~ cost + time | race_cat_re + lic_dum
                 + park_sub_cat + transit_sub_cat + veh_num + bike_num
                 + car_share_dum + income_cat_re, data = dat.logit, reflevel = "car")
summary(mod10)
lrtest(mod10, mod9)

## remove car_share_dum
mod11 <- mlogit (mode_cat ~ cost + time | race_cat_re + lic_dum
                 + park_sub_cat + transit_sub_cat + veh_num + bike_num
                 + income_cat_re, data = dat.logit, reflevel = "car")
summary(mod11)
lrtest(mod11, mod10)
AIC(mod11)
logLik_val <- logLik(mod11)
n <- nrow(dat.logit)
k <- length(coef(mod11))
bic_val <- -2 * as.numeric(logLik_val) + log(n) * k

table(dat$mode_cat,dat$park_sub_cat)
table(dat$mode_cat,dat$transit_sub_cat)
```

## Model results

### Model prediction

```{r intervention}
# driving cost
dat.1 <- dat
dat.1$cost.car <- dat.1$cost.car * 1.75
dat.1.logit <- mlogit.data(dat.1, shape="wide", 
                           choice="mode_cat", varying=c(20:25))

# transit time
dat.2 <- dat
dat.2$time.transit <- dat.2$time.transit * 1.75
dat.2.logit <- mlogit.data(dat.2, shape="wide", 
                           choice="mode_cat", varying=c(20:25))

# vehicle number
dat.3 <- dat
dat.3 <- dat.3 %>%
  mutate(veh_num = veh_num + 1)
dat.3.logit <- mlogit.data(dat.3, shape="wide", 
                           choice="mode_cat", varying=c(20:25))

# bike number
dat.4 <- dat
dat.4 <- dat.4 %>%
  mutate(bike_num = bike_num + 2)
dat.4.logit <- mlogit.data(dat.4, shape="wide", 
                           choice="mode_cat", varying=c(20:25))

# average predicted probability for using each mode before and after intervention
apply(predict(mod11, type = "response", newdata = dat.logit), 2, mean)
apply(predict(mod11, type = "response", newdata = dat.1.logit), 2, mean)
apply(predict(mod11, type = "response", newdata = dat.2.logit), 2, mean)
apply(predict(mod11, type = "response", newdata = dat.3.logit), 2, mean)
apply(predict(mod11, type = "response", newdata = dat.4.logit), 2, mean)
```

```{r prediction}
# predicting
mode.prob <- data.frame(predict(mod11, type = "response", newdata = dat.logit))
dat <- cbind.data.frame(dat, mode.prob)

dat$pred_mode <- 0

# use actual share in observed as thresholds
table(dat$mode_cat)/length(dat$mode_cat)

for (i in 1:length(dat$PERSON_ID)) {
  if (dat$car[i] > 0.659631) {
    dat$pred_mode[i] = "car"
  } else if (dat$transit[i] > 0.284960) {
    dat$pred_mode[i] = "transit"
  } else if (dat$bike[i] > 0.055409) {
    dat$pred_mode[i] = "bike"
  }
}

table(dat$pred_mode)/length(dat$pred_mode)
table(dat$mode_cat, dat$pred_mode)
table(dat$mode_cat)
```
